# Generated by Django 6.0.4 on 2026-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('operador', 'Operador')], default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
