# Generated by Django 6.0.4 on 2026-04-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_rol_perfil_direccion_perfil_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
    ]
