-- =========================================
-- Script de creación de tablas (Oracle)
-- Proyecto: Panoramas Web
-- =========================================

CREATE TABLE USUARIO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(150) NOT NULL,
    password VARCHAR2(128) NOT NULL,
    email VARCHAR2(254)
);

CREATE TABLE PERFIL (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR2(12) UNIQUE NOT NULL,
    telefono VARCHAR2(15),
    direccion VARCHAR2(200),
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_perfil_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES USUARIO(id)
);

CREATE TABLE CATEGORIA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE PANORAMA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    fecha DATE,
    lugar VARCHAR2(100),
    creador_id NUMBER NOT NULL,
    categoria_id NUMBER,
    CONSTRAINT fk_panorama_usuario
        FOREIGN KEY (creador_id)
        REFERENCES USUARIO(id),
    CONSTRAINT fk_panorama_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES CATEGORIA(id)
);